#!/usr/bin/env bash
# transfer a file to a remote server using ssh
if [ $# -le 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
if [ $# -gt 3 ]
then
    scp -o StrictHostKeyChecking=no -C -i "$4" "$1" "$3@$2":'~/'
fi
if [ $# -eq 3 ]
then
    scp -o StrictHostKeyChecking=no -C -i "$1" "$3@$2":'~/'
if
