#!/usr/bin/env bash
# creates a haproxy load balancer server
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0.\*
front_end="504.http\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend webbackend\n\nbackend webbackend\n\tbalance roundrobin\n\tserver web-01 104.196.19.203:8080 check\n\tserver web-02 104.196.170.235:8080 check"
sudo sed -i "s/504.http/$front_end/" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
