#!/usr/bin/env bash
# start a nginx server with port 80
cd /etc/nginx/sites-enabled/
sudo sed -i "s/listen 8080/ listen 80/" default
sedo sed -i "s/8080/80/" default
rm ./*~ || true
cd ~
sudo service nginx reload
sudo service nginx start
