#!/usr/bin/env bash
# start a nginx server with port 80
sudo sed -i "s/listen 8080/ listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-enabled/default~ || true
sudo service nginx reload
sudo service nginx start
