#!/usr/bin/env bash
# this script display numbers from 1 to 100 in a fizzbuzz format
num=1
while ((num <= 100));
do
	if ((num % 3 == 0 && num % 5 == 0));
	then
		echo "FizzBuzz";
	else
		if ((num % 3 == 0));
		then
		    echo "Fizz";
		elif ((num % 5 == 0));
		then
	     	    echo "Buzz";
		else
		    echo "$num";
		fi
	fi
	((num++));
done
