#!/usr/bin/env bash
# this script prints strings depending on the iteration in the while loop
STRING1="Holberton School";
STRING2="bad luck";
STRING3="good luck";
num=1;
while ((num <= 10));
do
	if ((num == 4));
	then
		echo "$STRING2";
	elif ((num == 8));
	then
		echo "$STRING3";
	else
		echo "$STRING1";
	fi
	((num++));
done
