#!/usr/bin/env bash
# script to display minutes and hours for 12 hours and 59 minutes with while loop
min=1
hours=0
while ((hours <= 12));
do
	echo "Hour: $hours";
	while ((min <= 59));
	do
		echo "$min";
		((min++));
	done
	((min=0))
	((hours++));
done
