#!/usr/bin/env bash
# this script tells you information about holbertonschool file
FILE=./holbertonschool
if test -f "$FILE";
then
	echo "holbertonschool file exists";
	if test -s "$FILE";
	then
		echo "holbertonschool file is not empty";
	else
		echo "holbertonschool file is empty";
	fi
	echo "holbertonschool is a regular file";
else
    if test -e "$FILE";
    then
	echo "holbertonschool file exists";
	if test -s "$FILE";
	then
            echo "holbertonschool file is not empty";
	else
            echo "holbertonschool file is empty";
	fi
    else
	echo "holbertonschool file does not exist";
    fi
fi
